-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 18:11:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema avdenterprise
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `avdenterprise` ;

-- -----------------------------------------------------
-- Schema avdenterprise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avdenterprise` DEFAULT CHARACTER SET utf8 ;
USE `avdenterprise` ;

-- -----------------------------------------------------
-- Table `avdenterprise`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`images` (
  `id` VARCHAR(150) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `key` VARCHAR(200) NOT NULL,
  `size` VARCHAR(100) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `createdup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `nameuser` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `createdup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_image` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_users_images1_idx` (`id_image` ASC) ,
  UNIQUE INDEX `nameuser_UNIQUE` (`nameuser` ASC) ,
  CONSTRAINT `fk_users_images1`
    FOREIGN KEY (`id_image`)
    REFERENCES `avdenterprise`.`images` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`evaluation_by_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`evaluation_by_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `createdup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT NULL DEFAULT 0,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk_evaluation_by_results_users1_idx` (`id_user` ASC) ,
  CONSTRAINT `fk_evaluation_by_results_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `avdenterprise`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`ebr_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`ebr_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `indicator` VARCHAR(100) NOT NULL,
  `goal` INT(100) NOT NULL,
  `createdup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_EBR` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_apr_metas_tb_apr1_idx` (`id_EBR` ASC) ,
  CONSTRAINT `fk_tb_apr_metas_tb_apr1`
    FOREIGN KEY (`id_EBR`)
    REFERENCES `avdenterprise`.`evaluation_by_results` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`ebr_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`ebr_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ebr_meta` INT NOT NULL,
  `answer` VARCHAR(100) NOT NULL,
  `createdup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_user` INT NOT NULL,
  `id_EBR` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_apr_result_tb_apr_metas1_idx` (`id_ebr_meta` ASC) ,
  INDEX `fk_tb_apr2_idx` (`id_EBR` ASC) ,
  INDEX `fk_user_idx` (`id_user` ASC) ,
  CONSTRAINT `fk_tb_apr_result_tb_apr_metas1`
    FOREIGN KEY (`id_ebr_meta`)
    REFERENCES `avdenterprise`.`ebr_items` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_apr2`
    FOREIGN KEY (`id_EBR`)
    REFERENCES `avdenterprise`.`evaluation_by_results` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `avdenterprise`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `createdup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_user` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_permissions_users1_idx` (`id_user` ASC) ,
  CONSTRAINT `fk_permissions_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `avdenterprise`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`user_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_permission` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_amd_has_permissoes_permissoes1_idx` (`id_permission` ASC) ,
  INDEX `fk_amd_has_permissoes_amd1_idx` (`id_user` ASC) ,
  CONSTRAINT `fk_amd_has_permissoes_amd1`
    FOREIGN KEY (`id_user`)
    REFERENCES `avdenterprise`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_amd_has_permissoes_permissoes1`
    FOREIGN KEY (`id_permission`)
    REFERENCES `avdenterprise`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `createdup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_user` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_units_users1_idx` (`id_user` ASC) ,
  CONSTRAINT `fk_units_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `avdenterprise`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`user_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`user_unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_unidade` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`, `id_unidade`, `id_user`),
  INDEX `fk_unidades_has_users_users1_idx` (`id_user` ASC) ,
  INDEX `fk_unidades_has_users_unidades1_idx` (`id_unidade` ASC) ,
  CONSTRAINT `fk_unidades_has_users_unidades1`
    FOREIGN KEY (`id_unidade`)
    REFERENCES `avdenterprise`.`units` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidades_has_users_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `avdenterprise`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`unit_ebr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`unit_ebr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_unit` INT NOT NULL,
  `id_ebr` INT NOT NULL,
  PRIMARY KEY (`id`, `id_unit`, `id_ebr`),
  INDEX `fk_units_has_evaluation_by_results_evaluation_by_results1_idx` (`id_ebr` ASC) ,
  INDEX `fk_units_has_evaluation_by_results_units1_idx` (`id_unit` ASC) ,
  CONSTRAINT `fk_units_has_evaluation_by_results_units1`
    FOREIGN KEY (`id_unit`)
    REFERENCES `avdenterprise`.`units` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_units_has_evaluation_by_results_evaluation_by_results1`
    FOREIGN KEY (`id_ebr`)
    REFERENCES `avdenterprise`.`evaluation_by_results` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
