-- MySQL Script generated by MySQL Workbench
-- Fri May 27 14:16:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema avdenterprise
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `avdenterprise` ;

-- -----------------------------------------------------
-- Schema avdenterprise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avdenterprise` DEFAULT CHARACTER SET utf8 ;
USE `avdenterprise` ;

-- -----------------------------------------------------
-- Table `avdenterprise`.`adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`adm` (
  `idadm` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(65) NOT NULL,
  `sobrenome` VARCHAR(65) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `cat` INT NOT NULL DEFAULT 1,
  `img` LONGTEXT NULL,
  `dataup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idadm`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`Unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`Unidades` (
  `idUnidades` INT NOT NULL AUTO_INCREMENT,
  `descri` VARCHAR(100) NOT NULL,
  `dateup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_adm` INT NOT NULL,
  PRIMARY KEY (`idUnidades`),
  INDEX `fk_id_adm_idx` (`id_adm` ASC) ,
  CONSTRAINT `fk_id_adm`
    FOREIGN KEY (`id_adm`)
    REFERENCES `avdenterprise`.`adm` (`idadm`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`gestor` (
  `idgestor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(65) NOT NULL,
  `sobrenome` VARCHAR(65) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `cat` INT NOT NULL DEFAULT 2,
  `img` LONGTEXT NULL,
  `id_adm` INT NOT NULL,
  `dataup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Unidades_idUnidades` INT NOT NULL,
  PRIMARY KEY (`idgestor`),
  INDEX `fk_gestor_amd1_idx` (`id_adm` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_gestor_Unidades1_idx` (`Unidades_idUnidades` ASC) ,
  CONSTRAINT `fk_gestor_amd1`
    FOREIGN KEY (`id_adm`)
    REFERENCES `avdenterprise`.`adm` (`idadm`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestor_Unidades1`
    FOREIGN KEY (`Unidades_idUnidades`)
    REFERENCES `avdenterprise`.`Unidades` (`idUnidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`tb_apr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`tb_apr` (
  `idtb_apr` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `dataup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_gestor_apr` INT NOT NULL,
  `status` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idtb_apr`, `id_gestor_apr`),
  INDEX `fk_tb_apr_gestor1_idx` (`id_gestor_apr` ASC) ,
  CONSTRAINT `fk_tb_apr_gestor1`
    FOREIGN KEY (`id_gestor_apr`)
    REFERENCES `avdenterprise`.`gestor` (`idgestor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`tb_apr_metas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`tb_apr_metas` (
  `idtb_metas` INT NOT NULL AUTO_INCREMENT,
  `indicador` VARCHAR(100) NOT NULL,
  `meta` INT(100) NOT NULL,
  `update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_tb_apr` INT NOT NULL,
  PRIMARY KEY (`idtb_metas`),
  INDEX `fk_tb_apr_metas_tb_apr1_idx` (`id_tb_apr` ASC) ,
  CONSTRAINT `fk_tb_apr_metas_tb_apr1`
    FOREIGN KEY (`id_tb_apr`)
    REFERENCES `avdenterprise`.`tb_apr` (`idtb_apr`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`col`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`col` (
  `idcol` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(65) NOT NULL,
  `sobrenome` VARCHAR(65) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `cat` INT NOT NULL DEFAULT 3,
  `img` LONGTEXT NULL,
  `id_gestor` INT NULL,
  `dataup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Unidades_idUnidades` INT NOT NULL,
  `id_adm` INT NOT NULL,
  PRIMARY KEY (`idcol`),
  INDEX `fk_col_gestor1_idx` (`id_gestor` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_col_Unidades1_idx` (`Unidades_idUnidades` ASC) ,
  INDEX `fk_adm_id_idx` (`id_adm` ASC) ,
  CONSTRAINT `fk_col_gestor1`
    FOREIGN KEY (`id_gestor`)
    REFERENCES `avdenterprise`.`gestor` (`idgestor`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_col_Unidades1`
    FOREIGN KEY (`Unidades_idUnidades`)
    REFERENCES `avdenterprise`.`Unidades` (`idUnidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adm_id`
    FOREIGN KEY (`id_adm`)
    REFERENCES `avdenterprise`.`adm` (`idadm`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`tb_apr_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`tb_apr_result` (
  `idtb_result` INT NOT NULL AUTO_INCREMENT,
  `id_tb_metas` INT NOT NULL,
  `resp` VARCHAR(100) NOT NULL,
  `dateup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `col_idcol` INT NOT NULL,
  `id_tb_apr` INT NOT NULL,
  PRIMARY KEY (`idtb_result`),
  INDEX `fk_tb_apr_result_tb_apr_metas1_idx` (`id_tb_metas` ASC) ,
  INDEX `fk_tb_apr_result_col1_idx` (`col_idcol` ASC) ,
  INDEX `fk_tb_apr2_idx` (`id_tb_apr` ASC) ,
  CONSTRAINT `fk_tb_apr_result_tb_apr_metas1`
    FOREIGN KEY (`id_tb_metas`)
    REFERENCES `avdenterprise`.`tb_apr_metas` (`idtb_metas`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_apr_result_col1`
    FOREIGN KEY (`col_idcol`)
    REFERENCES `avdenterprise`.`col` (`idcol`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_apr2`
    FOREIGN KEY (`id_tb_apr`)
    REFERENCES `avdenterprise`.`tb_apr` (`idtb_apr`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`apr_com_col`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`apr_com_col` (
  `id_tb_apr` INT NOT NULL,
  `col_idcol` INT NOT NULL,
  PRIMARY KEY (`id_tb_apr`, `col_idcol`),
  INDEX `fk_tb_apr_has_col_col1_idx` (`col_idcol` ASC) ,
  INDEX `fk_tb_apr_has_col_tb_apr1_idx` (`id_tb_apr` ASC) ,
  CONSTRAINT `fk_tb_apr_has_col_tb_apr1`
    FOREIGN KEY (`id_tb_apr`)
    REFERENCES `avdenterprise`.`tb_apr` (`idtb_apr`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_apr_has_col_col1`
    FOREIGN KEY (`col_idcol`)
    REFERENCES `avdenterprise`.`col` (`idcol`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`permissoes` (
  `idper` INT NOT NULL AUTO_INCREMENT,
  `descri` VARCHAR(100) NOT NULL,
  `dateup` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idper`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`adm_com_permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`adm_com_permissoes` (
  `adm_idadm` INT NOT NULL,
  `permissoes_idper` INT NOT NULL,
  PRIMARY KEY (`adm_idadm`, `permissoes_idper`),
  INDEX `fk_amd_has_permissoes_permissoes1_idx` (`permissoes_idper` ASC) ,
  INDEX `fk_amd_has_permissoes_amd1_idx` (`adm_idadm` ASC) ,
  CONSTRAINT `fk_amd_has_permissoes_amd1`
    FOREIGN KEY (`adm_idadm`)
    REFERENCES `avdenterprise`.`adm` (`idadm`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_amd_has_permissoes_permissoes1`
    FOREIGN KEY (`permissoes_idper`)
    REFERENCES `avdenterprise`.`permissoes` (`idper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`gestor_com_permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`gestor_com_permissoes` (
  `gestor_idgestor` INT NOT NULL,
  `permissoes_idper` INT NOT NULL,
  PRIMARY KEY (`gestor_idgestor`, `permissoes_idper`),
  INDEX `fk_gestor_has_permissoes_permissoes1_idx` (`permissoes_idper` ASC) ,
  INDEX `fk_gestor_has_permissoes_gestor1_idx` (`gestor_idgestor` ASC) ,
  CONSTRAINT `fk_gestor_has_permissoes_gestor1`
    FOREIGN KEY (`gestor_idgestor`)
    REFERENCES `avdenterprise`.`gestor` (`idgestor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestor_has_permissoes_permissoes1`
    FOREIGN KEY (`permissoes_idper`)
    REFERENCES `avdenterprise`.`permissoes` (`idper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avdenterprise`.`col_com_permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avdenterprise`.`col_com_permissoes` (
  `col_idcol` INT NOT NULL,
  `permissoes_idper` INT NOT NULL,
  PRIMARY KEY (`col_idcol`, `permissoes_idper`),
  INDEX `fk_col_has_permissoes_permissoes1_idx` (`permissoes_idper` ASC) ,
  INDEX `fk_col_has_permissoes_col1_idx` (`col_idcol` ASC) ,
  CONSTRAINT `fk_col_has_permissoes_col1`
    FOREIGN KEY (`col_idcol`)
    REFERENCES `avdenterprise`.`col` (`idcol`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_col_has_permissoes_permissoes1`
    FOREIGN KEY (`permissoes_idper`)
    REFERENCES `avdenterprise`.`permissoes` (`idper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
